// <auto-generated />
using System;
using FriendsApplicationApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FriendsApplicationApi.Migrations
{
    [DbContext(typeof(FriendsDBContext))]
    partial class FriendsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FriendsApplicationApi.Models.Friends", b =>
                {
                    b.Property<Guid>("friend_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("usersuser_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("friend_id");

                    b.HasIndex("usersuser_id");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("FriendsApplicationApi.Models.Users", b =>
                {
                    b.Property<Guid>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("User_id");

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("User_Email");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("User_Name");

                    b.Property<string>("user_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("User_Password");

                    b.Property<string>("user_surname")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("User_Surname");

                    b.HasKey("user_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("FriendsApplicationApi.Models.Friends", b =>
                {
                    b.HasOne("FriendsApplicationApi.Models.Users", "users")
                        .WithMany("Friends")
                        .HasForeignKey("usersuser_id");

                    b.Navigation("users");
                });

            modelBuilder.Entity("FriendsApplicationApi.Models.Users", b =>
                {
                    b.Navigation("Friends");
                });
#pragma warning restore 612, 618
        }
    }
}
